# This is a basic workflow to help you get started with Actions

name: Post Welcome comment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    types: opened

permissions:
    pull-requests: write
jobs:
  welcome:
    name: Post Welcome comment
    runs-on: ubuntu-latest

